name: github issue automation
on:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshcarp/predicate@v0.0.6
