name: github issue automation
on:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshcarp/predicate@9e61caf086d420b1adcd979c5a16395bcf63f1c9
